version: "3.8"
services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    # mysqlのコンテナが立ち上がるまで待つ
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    # 異常終了時に自動で再起動する
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    
